# Generated by Django 4.1.3 on 2022-11-14 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Divisions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_division', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('surname', models.CharField(max_length=80)),
                ('phone', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('url_photo', models.URLField(max_length=255)),
                ('biography', models.TextField(blank=True, null=True)),
                ('data_entry', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_role', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Subdivisions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_subdivision', models.CharField(max_length=25)),
                ('id_division', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='API.divisions')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeesSubdivisions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='API.employees')),
                ('id_subdivision', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='API.subdivisions')),
            ],
        ),
        migrations.AddField(
            model_name='employees',
            name='id_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='API.roles'),
        ),
    ]
